library (data.table)
mydata <- read_csv(dataframe.csv)
colnames(mydata)
setnames(mydata, "Teachers received written feedback and/or verbal feedback after every observation, formal and informal", "Teachers received feedback")
View(mydata)
setnames(mydata, "Teachers experienced more tailored development due to an increased knowledge of their performance", "It helped improve PD")
setnames(mydata, "I had successful conversations with teachers that linked student data to feedback I had about their teaching practice", "Successfully linked student data to teaching practice")
setnames(mydata, "I effectively facilitated difficult conversations with teachers whose performance was not meeting expectations", "It helped better communicate with teachers with low performance")
setnames(mydata, "Assigning observation ratings to teachers based on evidence from classroom observations", "Rate teachers based on teaching observation")
setnames(mydata, "I was successful at implementing Measures of Student Learning", "Successfully measured student learning"  )
View(mydata)
write.csv(mydata, "cleaned_mydata.csv")
